### PR TITLE
Jedis set

### PR DESCRIPTION
**Pull request by xsuoownit**

### CODE REVIEW

**Comment by cchacin** [comment]
@xsuoownit can you rebase with master and take a llok to @danigrmartinez changes related to databases in redis?

**Comment by xsuoownit** [comment]
@cchacin do you want me to make `in database` part optional?

**Comment by xsuoownit** [comment]
@cchacin comments addressed

**Comment by xsuoownit** [comment]
I run the test with coverage for this class and got 100% coverage for class, method and line.

**Comment by cchacin** [comment]
:+1:

**Pull request merged**
